### ISSUE TITLE
Feature Request: Windows Support

### ISSUE THREAD

**Issue by ehaselwanter** [stephenpearson/kitchen-oci#11]
Are there any plans to support windows? Would be great :-) 

And I wonder if this project does move to the official oracle GitHub org?

**Comment by stephenpearson** [comment]
Hi @ehaselwanter, sorry for not getting back to you earlier.

I must confess that Windows support wasn't something I'd envisaged so you may have to help me out a bit here.  Could you clarify a little what you're looking for?  Do you mean to say that you're running ChefDK on a Windows workstation and the plugin isn't working on the windows client side, or is the problem to do with launching Windows instances in OCI?  Could you describe what happens when you attempt to do whatever it is you're trying to do?

**Comment by ehaselwanter** [comment]
Hi @stephenpearson, 

no problem. We are heavy user of kitchen-oci to test all our linux boxes. so chef code on linux ... currently we want to move our windows workloads to OCI too. So it is about running the chef code on windows boxes in the cloud. 

Maybe everything is already working and I just can not figure out how to configure an example. In that case an example config would help.

cheers
Edmund

**Comment by stephenpearson** [comment]
I think the problem may be that you have to use winrm rather than ssh if using the supplied Windows images.  Normally (i.e. outside of Kitchen) the initial password for the opc user has to be retrieved from the API or console and then Windows forces a password change on first login.  When running this using the winrm transport then I'm not sure how we would handle this inside the Kitchen driver.

Are you planning to use custom Windows images in Kitchen containing a fixed password?

**Comment by stephenpearson** [comment]
@ehaselwanter I was able to make this work as follows:

First I had to make a custom Windows image from the standard Oracle provided Windows 2016 Server image.  I reset the initial password for the opc user to something else.  I then ensured that ports tcp/5985 and tcp/5986 were accessible through the windows firewall and via the security list in OCI.  Then I made sure that winrm was remotely accessible by running `winrm quickconfig` from a command session running as Administrator and accepting the prompts.  Finally I shut the machine down, then clicked 'Stop' for the instance in the console, and then clicked 'Create Custom Image'.

When that was complete, I added the new image OCID into the following kitchen configuration file for my cookbook:
```
---
driver:
  name: oci

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows
    os_type: windows
    driver:
      # These are mandatory
      compartment_id: ocid1.compartment.....
      availability_domain: ....
      image_id: ocid1.image.....
      shape: VM.Standard2.2
      subnet_id: ocid1.subnet....

      # These are optional
      use_private_ip: false
      oci_config_file: ~/.oci/config
      oci_profile_name: DEFAULT
      ssh_keypath: "~/.ssh/id_rsa.pub"
    transport:
      name: winrm
      username: opc
      password: "<redacted>"

suites:
  - name: default
    run_list:
      - recipe[my_cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

I ran kitchen as follows:

```
[stephen@chef my_cookbook]$ kitchen converge
-----> Starting Kitchen (v1.24.0)
WARN: Unresolved specs during Gem::Specification.reset:
      bundler (>= 1.10)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Creating <default-windows>...
       [WinRM] Established

       Finished creating <default-windows> (9m14.09s).
-----> Converging <default-windows>...
... etc ...
```

**Comment by ehaselwanter** [comment]
@stephenpearson that sounds great. Will test this in the upcoming days. we definitely should find a way for setting a (known) password during bootstrap / the api call. Will investigate that matter

**Comment by ehaselwanter** [comment]
@stephenpearson do you see a way to provide a `cloudinit.ps1` like shown in: https://github.com/terraform-providers/terraform-provider-oci/tree/master/docs/examples/compute/windows#what-this-example-covers

**Comment by stephenpearson** [comment]
@ehaselwanter Thanks for those links.  That approach may work, and I was looking at extending the `.kitchen.yml` file in this kind of way:
```
      user_data:
        - type: x-shellscript
          inline: |
            #!/bin/bash
            touch /tmp/foo.txt
          filename: init.sh
```
.. and since the Windows images now contain cloud-init then that ought to work for Powershell too.  Unfortunately, so far I've not been able to inject the multipart-mime userdata into cloud-init successfully but I'll keep tinkering with it.

If this general approach does work, then using the examples you linked to it ought to be possible to enable winrm and set a password.  If we did set the password this way then it would imply that the userdata would have to contain the password in plaintext (or base64 encoded), so not very secure but probably good enough for spinning up a temporary test environment.
