### ISSUE TITLE
add ENV['USER'] to freeform tags

### ISSUE THREAD

**Issue by slippman** [stephenpearson/kitchen-oci#19]
@stephenpearson , what do you think of adding a freeform tag that identifies the user who created the instance? This may make it easier to search for instances that a specific user created. I am currently handling it like this: 
```      
hostname_prefix: gta-<%= ENV['USER'] %>
```
but in the case where someone decides to change that, it might be hard for them to find their node. 
Maybe we can add a freeform tag like owner, or created_by, or something like that?

**Comment by stephenpearson** [comment]
Hi @slippman.  Sorry for the delay in getting back to you.  I'm a little reluctant to add a myriad of tag options unless we can be sure that most users would want that by default.  Does something like this not work for you instead?
```yaml
platforms:
  - name: foo
    driver:
      freeform_tags:
        username: "<%= ENV['USER'] %>"
```
