### ISSUE TITLE
Create action failed with no error on debug

### ISSUE THREAD

**Issue by luckeyca** [stephenpearson/kitchen-oci#39]
Details:

1. command:  kitchen test --color --destroy always
2. Error:
-----> Starting Test Kitchen (v3.3.2)
-----> Cleaning up any prior instances of <ansible-role-autonomous-database-default-oci>
-----> Destroying <ansible-role-autonomous-database-default-oci>...
       Finished destroying <ansible-role-autonomous-database-default-oci> (0m0.00s).
-----> Testing <ansible-role-autonomous-database-default-oci>
-----> Creating <ansible-role-autonomous-database-default-oci>...
-----> Destroying <ansible-role-autonomous-database-default-oci>...
       Finished destroying <ansible-role-autonomous-database-default-oci> (0m0.00s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [undefined method `length' for nil:NilClass] on ansible-role-autonomous-database-default-oci
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

3. kitchen diagnose --all output
```
---
timestamp: 2023-02-14 20:40:59 UTC
kitchen_version: 3.3.2
plugins:
  driver:
    Oci:
      class: Kitchen::Driver::Oci
      version:
      api_version:
  provisioner:
    AnsiblePlaybook:
      class: Kitchen::Provisioner::AnsiblePlaybook
      version:
      api_version:
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 3.3.2
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 2.6.1
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/mnt/kitchen.yml"
    raw_data:
      provisioner:
        name: ansible_playbook
        hosts: localhost
        require_chef_for_busser: false
        ansible_connection: local
        ansible_verbose: true
        ansible_diff: true
        ansible_verbosity: 2
        idempotency_test: true
      driver:
        name: oci
      verifier:
        name: inspec
      platforms:
      - name: oci
        os_type: ubuntu
      suites:
      - name: ansible-role-autonomous-database-default
        driver:
          compartment_id: <masked>
          availability_domain: ZoCL:CA-TORONTO-1-AD-1
          shape: VM.Standard.E2.1.Micro
          subnet_id: <masked>
          instance_type: dbaas
          dbaas:
            db_version: 19c
            cpu_core_count: 1
            db_name: dbaas1
            admin_password: test123
            initial_data_storage_size_in_gb: 20
            db_workload: OLTP
          use_private_ip: false
        verifier:
          systems:
          - name: default
            provisioner:
            - test/integration/ansible-role-autonomous-database-default
            reporter:
            - cli
            - junit2:test/reports/ansible-role-autonomous-database-default-junit.xml
  local_config:
  combined_config:
    filename:
    raw_data:
      provisioner:
        name: ansible_playbook
        hosts: localhost
        require_chef_for_busser: false
        ansible_connection: local
        ansible_verbose: true
        ansible_diff: true
        ansible_verbosity: 2
        idempotency_test: true
      driver:
        name: oci
      verifier:
        name: inspec
      platforms:
      - name: oci
        os_type: ubuntu
      suites:
      - name: ansible-role-autonomous-database-default
        driver:
          compartment_id: <masked>
          availability_domain: ZoCL:CA-TORONTO-1-AD-1
          shape: VM.Standard.E2.1.Micro
          subnet_id: <masked>
          instance_type: dbaas
          dbaas:
            db_version: 19c
            cpu_core_count: 1
            db_name: dbaas1
            admin_password: test123
            initial_data_storage_size_in_gb: 20
            db_workload: OLTP
          use_private_ip: false
        verifier:
          systems:
          - name: default
            provisioner:
            - test/integration/ansible-role-autonomous-database-default
            reporter:
            - cli
            - junit2:test/reports/ansible-role-autonomous-database-default-junit.xml
instances:
  ansible-role-autonomous-database-default-oci:
    platform:
      os_type: ubuntu
      shell_type: bourne
    state_file: {}
    driver:
      availability_domain: ZoCL:CA-TORONTO-1-AD-1
      compartment_id: <masked>
      dbaas:
        db_version: 19c
        cpu_core_count: 1
        db_name: dbaas1
        admin_password: test123
        initial_data_storage_size_in_gb: 20
        db_workload: OLTP
      freeform_tags: {}
      hostname_prefix:
      image_id:
      instance_type: dbaas
      kitchen_root: "/mnt"
      log_level: :info
      name: oci
      oci_config_file:
      oci_profile_name:
      post_create_script:
      pre_create_command:
      preemptible_instance: false
      proxy_url:
      setup_winrm: false
      shape: VM.Standard.E2.1.Micro
      shape_config: {}
      ssh_keypath: "/root/.ssh/id_rsa.pub"
      subnet_id: <masked>
      test_base_path: "/mnt/test/integration"
      use_instance_principals: false
      use_private_ip: false
      user_data:
      winrm_password:
      winrm_user: opc
    provisioner:
      additional_copy_path:
      additional_copy_role_path: false
      additional_ssh_private_keys:
      ansible_apt_repo: ppa:ansible/ansible
      ansible_binary_path:
      ansible_cfg_overwrite: true
      ansible_cfg_path:
      ansible_check: false
      ansible_connection: local
      ansible_diff: true
      ansible_host_key_checking: true
      ansible_inventory:
      ansible_inventory_file:
      ansible_limit:
      ansible_omnibus_remote_path: "/opt/ansible"
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      ansible_platform: ''
      ansible_playbook_command:
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/openSUSE_Leap_15.2/systemsmanagement.repo
      ansible_source_rev:
      ansible_source_url: git://github.com/ansible/ansible.git
      ansible_sudo: true
      ansible_vault_password_file:
      ansible_verbose: true
      ansible_verbosity: 2
      ansible_version:
      ansible_yum_repo:
      ansiblefile_path:
      callback_plugins_path:
      chef_bootstrap_url: https://www.chef.io/chef/install.sh
      command_prefix:
      custom_post_install_command:
      custom_post_play_command:
      custom_pre_install_command:
      custom_pre_play_command:
      debug:
      downloads: {}
      enable_yum_epel: false
      env_vars: {}
      extra_vars: {}
      extra_vars_file:
      filter_plugins_path:
      ftp_proxy:
      galaxy_ignore_certs: false
      group_vars_path:
      host_vars_path:
      hosts: localhost
      http_proxy:
      https_proxy:
      idempotency_skip_tags: []
      idempotency_tags: []
      idempotency_test: true
      ignore_ansible_cfg: false
      ignore_extensions_from_root:
      - ".pyc"
      ignore_paths_from_root: []
      keep_playbook_path: false
      kerberos_conf_file:
      kitchen_root: "/mnt"
      library_plugins_path:
      lookup_plugins_path:
      max_retries: 1
      modules_path:
      name: ansible_playbook
      no_proxy:
      playbook: "/mnt/test/integration/ansible-role-autonomous-database-default/default.yml"
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Leap_15.2/devel:languages:python.repo
      recursive_additional_copy_path:
      require_ansible_omnibus: false
      require_ansible_repo: true
      require_ansible_source: false
      require_chef_for_busser: false
      require_pip: false
      require_pip3: false
      require_ruby_for_busser: false
      require_windows_support: false
      requirements_collection_path: false
      requirements_path: false
      retry_on_exit_code: []
      role_name:
      roles_path: "/mnt"
      root_path: "/tmp/kitchen"
      shell_command: sh
      show_command_output: false
      ssh_known_hosts:
      sudo: true
      sudo_command: sudo -E
      tags: []
      test_base_path: "/mnt/test/integration"
      update_package_repos: true
      uploads: {}
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      keepalive_maxcount: 3
      kitchen_root: "/mnt"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_port: 22
      ssh_gateway_username:
      ssh_http_proxy:
      ssh_http_proxy_password:
      ssh_http_proxy_port:
      ssh_http_proxy_user:
      ssh_key:
      test_base_path: "/mnt/test/integration"
      username: root
    verifier:
      backend_cache: true
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/mnt"
      load_plugins: true
      log_level: :info
      name: inspec
      plugin_config: {}
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: ansible-role-autonomous-database-default
      systems:
      - name: default
        provisioner:
        - test/integration/ansible-role-autonomous-database-default
        reporter:
        - cli
        - junit2:test/reports/ansible-role-autonomous-database-default-junit.xml
      test_base_path: "/mnt/test/integration"
    lifecycle_hooks:
      debug:
      kitchen_root: "/mnt"
      log_level: :info
      test_base_path: "/mnt/test/integration"
```
4. kitchen.yml file content
```
---
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  ansible_connection: local
  ansible_verbose: true
  ansible_diff: true
  ansible_verbosity: 2
  idempotency_test: true

driver:
  name: oci

verifier:
  name: inspec

platforms:
  - name: oci
    os_type: ubuntu

suites: # To add more test suites, copy/paste the whole section below and update the lines with inline comments as needed.
  - name: ansible-role-autonomous-database-default
    driver:
      # These are mandatory
      compartment_id: <masked>
      availability_domain: ZoCL:CA-TORONTO-1-AD-1
      shape: VM.Standard.E2.1.Micro
      subnet_id: <masked>
      instance_type: dbaas # If omit, default is compute
      dbaas: # Required for dbaas instance_type
        db_version: 19c
        cpu_core_count: 1 # Free tier is 1 OCPU
        db_name: dbaas1
        admin_password: <masked>
        initial_data_storage_size_in_gb: 20 # Free tier is 20GB
        db_workload: OLTP # Acceptable values are 'OLTP' and 'DSS'. Default value is 'OLTP'
      # These are optional
      use_private_ip: false # Required to be false when using free tier
    verifier:
      systems:
      - name: default # Name for the test instance
        provisioner: # Directory under which the test cases are. If omit, default is <KITCHEN ROOT>/test/integration/<KITCHEN SUITE NAME>
          - test/integration/ansible-role-autonomous-database-default
        reporter: # test result outputs. cli for stdout. junit2 for pipeline use. 
          - cli # DO NOT REMOVE. It's useful for troubleshooting on pipeline terminal.
          - junit2:test/reports/ansible-role-autonomous-database-default-junit.xml # Make sure the file name is *-junit.xml under test/reports directory as pipeline looks for it.
```
