### ISSUE TITLE
Feature Request: Add ProxyCommand support

### ISSUE THREAD

**Issue by luckeyca** [stephenpearson/kitchen-oci#79]
We only have private subnets in our OCI tenants. It would be great to have ProxyCommand support in kitchen oci so that after the VM is provisioned, test kitchen running on managed CI services on internet access access the provisioned VM on OCI private subnet through OCI bastion service.

**Comment by justintsteele** [comment]
have you tried using the proxy settings that are available in the `provisioner` section of the kitchen.yml? that is typically where this type of thing is handled:

```yaml
---
provisioner:
  https_proxy: http://myproxy.com
  http_proxy: http://myproxy.com
  no_proxy: *.internal.com
```
